Document: lliurex-statistics
Title: Debian lliurex-statistics Manual
Author: <insert document author here>
Abstract: This manual describes what lliurex-statistics is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/lliurex-statistics/lliurex-statistics.sgml.gz

Format: postscript
Files: /usr/share/doc/lliurex-statistics/lliurex-statistics.ps.gz

Format: text
Files: /usr/share/doc/lliurex-statistics/lliurex-statistics.text.gz

Format: HTML
Index: /usr/share/doc/lliurex-statistics/html/index.html
Files: /usr/share/doc/lliurex-statistics/html/*.html
